server:
  port: 8080

app:
  kafka:
    topic: payments

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8085}
      auto.register.schemas: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-url: https://YOUR-ADFS-DOMAIN/adfs

management.endpoints.web.exposure.include: health,info,metrics